import { Link, useRouterState } from "@tanstack/react-router";
import { Menu, Search, ShoppingBag, UserRound, X, Instagram, Facebook } from "lucide-react";
import { useEffect, useState } from "react";
import { Brand } from "./Brand"; import { useCart } from "@/context/CartContext";
const links=[['/','Accueil'],['/creations','Les créations'],['/ourika','Ourika'],['/atelier','L’atelier'],['/ahmed-tiziri','Ahmed Tiziri'],['/contact','Contact']] as const;
export function Header(){const path=useRouterState({select:s=>s.location.pathname});const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const {count}=useCart();const hero=path==='/'||path==='/ourika'||path==='/atelier'||path==='/ahmed-tiziri';useEffect(()=>{const f=()=>setScrolled(scrollY>40);f();addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);useEffect(()=>setOpen(false),[path]);const light=hero&&!scrolled;
return <><header className={`fixed inset-x-0 top-0 z-50 transition-all duration-700 ${scrolled?'border-b border-border/60 bg-background/90 backdrop-blur-md':'bg-transparent'} ${light?'text-hero-foreground':'text-foreground'}`}><div className="mx-auto grid h-22 max-w-[1500px] grid-cols-[auto_1fr_auto] items-center gap-8 px-5 lg:px-12"><Brand light={light}/><nav className="hidden justify-center gap-7 lg:flex">{links.map(([to,label])=><Link key={to} to={to} activeOptions={{exact:to==='/'}} className="nav-link" activeProps={{className:'nav-link is-active'}}>{label}</Link>)}</nav><div className="flex items-center justify-end gap-1"><button className="icon-button hidden sm:grid" aria-label="Rechercher"><Search/></button><button className="icon-button hidden sm:grid" aria-label="Compte"><UserRound/></button><Link to="/panier" className="icon-button relative" aria-label={`Panier, ${count} articles`}><ShoppingBag/><span className="cart-count">{count}</span></Link><button className="icon-button lg:hidden" onClick={()=>setOpen(true)} aria-label="Ouvrir le menu"><Menu/></button></div></div></header>
<div className={`fixed inset-0 z-[60] bg-ink text-hero-foreground transition-transform duration-700 ${open?'translate-x-0':'translate-x-full'}`}><div className="flex h-22 items-center justify-between px-6"><Brand light/><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Fermer le menu"><X/></button></div><nav className="flex h-[calc(100%-5.5rem)] flex-col items-center justify-center gap-6">{links.map(([to,label],i)=><Link key={to} to={to} className="font-serif text-4xl italic">{String(i+1).padStart(2,'0')} — {label}</Link>)}</nav></div></>}
export function Footer(){return <footer className="bg-ink px-6 py-16 text-hero-foreground"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_1fr]"><div><Brand light/><p className="mt-7 font-serif text-2xl italic">Porter la nature.<br/>Porter une histoire.</p></div><div className="grid grid-cols-2 gap-8 text-xs uppercase tracking-[.16em]"><div className="grid gap-4">{links.slice(1).map(([to,l])=><Link key={to} to={to}>{l}</Link>)}</div><div className="grid gap-4"><Link to="/mentions-legales">Mentions légales</Link><Link to="/confidentialite">Confidentialité</Link><Link to="/conditions">Conditions générales</Link><div className="flex gap-4 pt-2"><Instagram/><Facebook/></div></div></div></div><div className="mx-auto mt-14 max-w-7xl border-t border-hero-foreground/20 pt-5 text-[.65rem] uppercase tracking-[.14em] opacity-60">© 2026 Tiziri · Ourika, Maroc</div></footer>}
