/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AhmedTiziriRouteImport } from './routes/ahmed-tiziri'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as OurikaRouteImport } from './routes/ourika'
import { Route as CreationsSlugRouteImport } from './routes/creations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AhmedTiziriRoute = AhmedTiziriRouteImport.update({
  id: '/ahmed-tiziri',
  path: '/ahmed-tiziri',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const OurikaRoute = OurikaRouteImport.update({
  id: '/ourika',
  path: '/ourika',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsSlugRoute = CreationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CreationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ahmed-tiziri': typeof AhmedTiziriRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRouteWithChildren
  '/ourika': typeof OurikaRoute
  '/creations/$slug': typeof CreationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ahmed-tiziri': typeof AhmedTiziriRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRouteWithChildren
  '/ourika': typeof OurikaRoute
  '/creations/$slug': typeof CreationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ahmed-tiziri': typeof AhmedTiziriRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRouteWithChildren
  '/ourika': typeof OurikaRoute
  '/creations/$slug': typeof CreationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ahmed-tiziri'
    | '/atelier'
    | '/contact'
    | '/creations'
    | '/ourika'
    | '/creations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ahmed-tiziri'
    | '/atelier'
    | '/contact'
    | '/creations'
    | '/ourika'
    | '/creations/$slug'
  id:
    | '__root__'
    | '/'
    | '/ahmed-tiziri'
    | '/atelier'
    | '/contact'
    | '/creations'
    | '/ourika'
    | '/creations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AhmedTiziriRoute: typeof AhmedTiziriRoute
  AtelierRoute: typeof AtelierRoute
  ContactRoute: typeof ContactRoute
  CreationsRoute: typeof CreationsRouteWithChildren
  OurikaRoute: typeof OurikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ahmed-tiziri': {
      id: '/ahmed-tiziri'
      path: '/ahmed-tiziri'
      fullPath: '/ahmed-tiziri'
      preLoaderRoute: typeof AhmedTiziriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ourika': {
      id: '/ourika'
      path: '/ourika'
      fullPath: '/ourika'
      preLoaderRoute: typeof OurikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/$slug': {
      id: '/creations/$slug'
      path: '/$slug'
      fullPath: '/creations/$slug'
      preLoaderRoute: typeof CreationsSlugRouteImport
      parentRoute: typeof CreationsRoute
    }
  }
}

interface CreationsRouteChildren {
  CreationsSlugRoute: typeof CreationsSlugRoute
}

const CreationsRouteChildren: CreationsRouteChildren = {
  CreationsSlugRoute: CreationsSlugRoute,
}

const CreationsRouteWithChildren = CreationsRoute._addFileChildren(
  CreationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AhmedTiziriRoute: AhmedTiziriRoute,
  AtelierRoute: AtelierRoute,
  ContactRoute: ContactRoute,
  CreationsRoute: CreationsRouteWithChildren,
  OurikaRoute: OurikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
