/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AhmedTiziriRouteImport } from './routes/ahmed-tiziri'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as OurikaRouteImport } from './routes/ourika'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as CreationsIndexRouteImport } from './routes/creations.index'
import { Route as CreationsSlugRouteImport } from './routes/creations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AhmedTiziriRoute = AhmedTiziriRouteImport.update({
  id: '/ahmed-tiziri',
  path: '/ahmed-tiziri',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const OurikaRoute = OurikaRouteImport.update({
  id: '/ourika',
  path: '/ourika',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsIndexRoute = CreationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreationsRoute,
} as any)
const CreationsSlugRoute = CreationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CreationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ahmed-tiziri': typeof AhmedTiziriRoute
  '/atelier': typeof AtelierRoute
  '/checkout': typeof CheckoutRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/ourika': typeof OurikaRoute
  '/panier': typeof PanierRoute
  '/creations/$slug': typeof CreationsSlugRoute
  '/creations/': typeof CreationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ahmed-tiziri': typeof AhmedTiziriRoute
  '/atelier': typeof AtelierRoute
  '/checkout': typeof CheckoutRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/ourika': typeof OurikaRoute
  '/panier': typeof PanierRoute
  '/creations/$slug': typeof CreationsSlugRoute
  '/creations': typeof CreationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ahmed-tiziri': typeof AhmedTiziriRoute
  '/atelier': typeof AtelierRoute
  '/checkout': typeof CheckoutRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/ourika': typeof OurikaRoute
  '/panier': typeof PanierRoute
  '/creations/$slug': typeof CreationsSlugRoute
  '/creations/': typeof CreationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ahmed-tiziri'
    | '/atelier'
    | '/checkout'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/creations'
    | '/mentions-legales'
    | '/ourika'
    | '/panier'
    | '/creations/$slug'
    | '/creations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ahmed-tiziri'
    | '/atelier'
    | '/checkout'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/ourika'
    | '/panier'
    | '/creations/$slug'
    | '/creations'
  id:
    | '__root__'
    | '/'
    | '/ahmed-tiziri'
    | '/atelier'
    | '/checkout'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/creations'
    | '/mentions-legales'
    | '/ourika'
    | '/panier'
    | '/creations/$slug'
    | '/creations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AhmedTiziriRoute: typeof AhmedTiziriRoute
  AtelierRoute: typeof AtelierRoute
  CheckoutRoute: typeof CheckoutRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CreationsRoute: typeof CreationsRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OurikaRoute: typeof OurikaRoute
  PanierRoute: typeof PanierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ahmed-tiziri': {
      id: '/ahmed-tiziri'
      path: '/ahmed-tiziri'
      fullPath: '/ahmed-tiziri'
      preLoaderRoute: typeof AhmedTiziriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ourika': {
      id: '/ourika'
      path: '/ourika'
      fullPath: '/ourika'
      preLoaderRoute: typeof OurikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/': {
      id: '/creations/'
      path: '/'
      fullPath: '/creations/'
      preLoaderRoute: typeof CreationsIndexRouteImport
      parentRoute: typeof CreationsRoute
    }
    '/creations/$slug': {
      id: '/creations/$slug'
      path: '/$slug'
      fullPath: '/creations/$slug'
      preLoaderRoute: typeof CreationsSlugRouteImport
      parentRoute: typeof CreationsRoute
    }
  }
}

interface CreationsRouteChildren {
  CreationsSlugRoute: typeof CreationsSlugRoute
  CreationsIndexRoute: typeof CreationsIndexRoute
}

const CreationsRouteChildren: CreationsRouteChildren = {
  CreationsSlugRoute: CreationsSlugRoute,
  CreationsIndexRoute: CreationsIndexRoute,
}

const CreationsRouteWithChildren = CreationsRoute._addFileChildren(
  CreationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AhmedTiziriRoute: AhmedTiziriRoute,
  AtelierRoute: AtelierRoute,
  CheckoutRoute: CheckoutRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CreationsRoute: CreationsRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OurikaRoute: OurikaRoute,
  PanierRoute: PanierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
